{% set name = "types-jsonschema" %}
{% set version = "4.23.0.20241208" %}

package:
  name: types-jsonschema
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/t/{{ name }}/types_jsonschema-{{ version }}.tar.gz
    sha256: e8b15ad01f290ecf6aea53f93fbdf7d4730e4600313e89e8a7f95622f7e87b7c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<38]

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - python
    - referencing
  run_constrained:
    - pytest >=4.6
    - coverage >=7.5

test:
  imports:
    - types
  requires:
    - pip
  commands:
    - pip check
    - test -f $SP_DIR/jsonschema-stubs/__init__.pyi  # [unix]
    - if not exist %SP_DIR%\\jsonschema-stubs\\__init__.pyi exit 1  # [win]

about:
  home: https://github.com/python/typeshed
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Typing stubs for jsonschema
  description: |
    This is a PEP 561 type stub package for the jsonschema package. It can be
    used by type-checking tools like mypy, pyright, pytype, PyCharm, etc. to
    check code that uses jsonschema.
  dev_url: https://github.com/python/typeshed
  doc_url: https://python-jsonschema.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - conda-forge/mypy