{% set name = "types-jsonschema" %}
{% set version = "4.25.1.20251008" %}

package:
  name: types-jsonschema
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/t/types-jsonschema/types_jsonschema-4.25.1.20251008.tar.gz
    sha256: f206abf739c2d84f46632b65db99474a2e3b2f651df417c491ff038022c89c10

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - setuptools >=77.0.3
  run:
    - python
    - referencing

test:
  imports:
    - types
  requires:
    - pip
  commands:
    - pip check
    - test -f $SP_DIR/jsonschema-stubs/__init__.pyi  # [unix]
    - if not exist %SP_DIR%\\jsonschema-stubs\\__init__.pyi exit 1  # [win]

about:
  home: https://github.com/python/typeshed
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Typing stubs for jsonschema
  description: |
    This is a PEP 561 type stub package for the jsonschema package. It can be
    used by type-checking tools like mypy, pyright, pytype, PyCharm, etc. to
    check code that uses jsonschema.
  dev_url: https://github.com/python/typeshed
  doc_url: https://python-jsonschema.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - conda-forge/mypy
