{% set name = "types-jsonschema" %}
{% set version = "4.19.0.4" %}

package:
  name: types-jsonschema
  version: {{ version }}


source:
  - url: https://pypi.io/packages/source/t/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 994feb6632818259c4b5dbd733867824cb475029a6abc2c2b5201a2268b6e7d2


build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<36]


requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - python
    - referencing


test:
  imports:
    - types
  requires:
    - pip
  commands:
    - pip check
    - test -f $SP_DIR/jsonschema-stubs/__init__.pyi                 # [unix]
    - if not exist %SP_DIR%\\jsonschema-stubs\\__init__.pyi exit 1  # [win]


about:
  home: https://github.com/python/typeshed
  license: Apache-2.0 AND MIT
  license_file: LICENSE
  license_family: OTHER
  summary: Typing stubs for jsonschema
  description: |
    This is a PEP 561 type stub package for the jsonschema package. It can be
    used by type-checking tools like mypy, pyright, pytype, PyCharm, etc. to
    check code that uses jsonschema.
  dev_url: https://github.com/python/typeshed
  doc_url: https://json-schema.org/learn/getting-started-step-by-step


extra:
  recipe-maintainers:
    - conda-forge/mypy
