{% set name = "types-jsonschema" %}
{% set version = "4.25.1.20251009" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
    sha256: 75d0f5c5dd18dc23b664437a0c1a625743e8d2e665ceaf3aecb29841f3a5f97f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - setuptools >=77.0.3
  run:
    - python
    - referencing

test:
  imports:
    - types
  commands:
    - pip check
    - test -f $SP_DIR/jsonschema-stubs/__init__.pyi                 # [unix]
    - if not exist %SP_DIR%\\jsonschema-stubs\\__init__.pyi exit 1  # [win]
  requires:
    - pip

about:
  home: https://github.com/python/typeshed
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Typing stubs for jsonschema
  description: |
    This is a PEP 561 type stub package for the jsonschema package. It can be
    used by type-checking tools like mypy, pyright, pytype, PyCharm, etc. to
    check code that uses jsonschema.
  dev_url: https://github.com/python/typeshed
  doc_url: https://python-jsonschema.readthedocs.io

extra:
  recipe-maintainers:
    - conda-forge/mypy
